# Note: Smaller values result in less lag. Lift speed less than 0.4 may not work well for non spout servers.
# autoPlace will automatically move players to be fully in the elevator
# checkGlass will make sure all floors have glass blocks (at the cost of possible lag when starting a lift)
# preventEntry will prevent players from entering an active elevator (at the cost of possible lag when lifts are running) 
maxLiftArea: 16
maxHeight: 256
debug: false
autoPlace: false
preventEntry: false
preventLeave: true
checkFloor: false
liftMobs: true
floorBlocks:
- GLASS
- STAINED_GLASS
redstone: false
baseBlockSpeeds:
  IRON_BLOCK: 0.5
STRING_oneFloor: <电梯> 只有1层楼...
STRING_currentFloor: '<电梯> 当前楼层:'
STRING_dest: '<电梯> 目的地:'
STRING_cantEnter: <电梯> 正在使用中,无法进入...
STRING_cantLeave: <电梯> 正在使用中.无法离开...
