Enabled: true
Spawning:
  BlockedMobs:
  - BLAZE
  - CAVE_SPIDER
  - CREEPER
  - GHAST
  - GIANT
  - ZOMBIE
  - GUARDIAN
  - IRON_GOLEM
  - MAGMA_CUBE
  - PIG_ZOMBIE
  - WITHER
  - SILVERFISH
  - SKELETON
  - SLIME
  - SNOWMAN
  - SPIDER
  - WITCH
  - MAGMA_CUBE
  - HORSE
  - BAT
  - PIG
  - COW
  - MUSHROOM_COW
  - CHICKEN
  - OCELOT
  - RABBIT
  - SHEEP
  - SQUID
  - VILLAGER
  - WOLF
